using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KafkaConsumer
{
    public enum EKafkaTopic_old
    {
        None = 0,
        Monitor,
        TestInfo,
        Channel,
        Auxiliary,
        CANBMS,
        SMB,
        Event,
        DiagnosticEvent,
        SubChannel,
    }
    public enum EKafkaTopic
    {
        None = 0,
        ChannelMonitorData,
        ChannelTestInfoData,
        ChannelData,
        Auxiliary,
        CANBMS,
        SMB,
        ChannelEventData,
        ChannelDiagnosticEventData,
        SubChannelData,
    }
    public enum EMonitorFieldPos
    {
        SerialNumber = 0,
        Barcode = 1,
        TestName,
        Channel,
        ExitCondition,
        Status,
        TestTime,
        StepTime,
        Cycle,
        Step,
        Current,
        Voltage,
        Power,
        ChargeCapatity,
        DischargeCapatity,
        ChargeEnergy,
        DischargeEnergy,
        InternalResistance,
        dVdt,
        dQdV,
        dVdQ,
        Aux,
        Aux_AuxType = 0,
        Aux_AliasName = 1,
        Aux_AuxChGlobalID = 2,
        Aux_AuxChVirtualID = 3,
        Aux_Value = 4,
        Aux_dxdt = 5,
        CANBMS_MetaName = 0,
        CANBMS_AliasName = 1,
        CANBMS_IsOffline = 2,
        CANBMS_DataType = 3,
        CANBMS_Value = 4,
        SMB_MetaName = 0,
        SMB_AliasName = 1,
        SMB_IsOffline = 2,
        SMB_DataType = 3,
        SMB_Value = 4,
        SimulationName = 0,
        Mapping_AuxType = 0,
        Mapping_AuxChGlobalID = 1,
        Mapping_AliasName = 2,
        Mapping_Unit = 3,
        Channel_SerialNumber = 0,
        Channel_Barcode = 1,
        Channel_TestName = 2,
        Channel_TestID = 3,
        Channel_Chan = 4,
        Channel_DateTime,
        Channel_DataPoint,
        Channel_Status,
        Channel_TestTime,
        Channel_Steptime,
        Channel_CycleID,
        Channel_StepID,
        Channel_Current,
        Channel_Voltage,
        Channel_Power,
        Channel_ChargeCapatity,
        Channel_DischargeCapatity,
        Channel_ChargeEnergy,
        Channel_DischargeEnergy,
        Channel_InternalResistance, 
        Channel_dVdt,
        Channel_dQdV,
        Channel_dVdQ,
        Channel_Aux,
        Channel_CANBMSs,
        Channel_SMBs,
        Channel_SMB_MetaName = 0,
        Channel_SMB_AliasName = 1,
        Channel_SMB_DataType = 2,
        Channel_SMB_Value = 3,
        Channel_CANBMS_MetaName = 0,
        Channel_CANBMS_AliasName = 1,
        Channel_CANBMS_DataType = 2,
        Channel_CANBMS_Value = 3,
    }
    public enum EChannelStatus : int
    {
        Idle,
        Transition,
        Charge,
        DisCharge,
        Rest,
        Wait,
        ExternalCharge,
        Calibration,
        Unsafe,
        Pulse,
        IR,
        ACI,
        MCellACI,
        AddIn,
        Error,
        Finished,
        VoltMeter,
        WaitingACS,
        Pause,
        Empty,
        IdleMcu,
        Start,
        Running,
        StepTransfer,
        Resume,
        GoPause,
        GoStop,
        GoNextStep,
        OnlineUpdata,
        DaqMemoryUnsafe,
        ACR,
        Suspent,
        MaxCount,
    }
    public enum EAuxColumn
    {
        Aux_Voltage = 0,
        Aux_Temperature,
        Aux_Pressure,
        Aux_PH,
        Aux_FlowRate,
        Aux_Density,
        Aux_DigitalInput,
        Aux_DigitalOutput,
        Aux_EC,
        Aux_Safety,
        Aux_Humidity,
        Aux_AnalogOutput,
        Aux_Current,
    }
    public enum EMessageFormat
    {
        AVRO,
        JSON,
    }
}
